language: c # vala is not supported, but c comes with closest dependencies

install:
  - sudo add-apt-repository -y ppa:vala-team # travis currently runs ubuntu 12.04, so we have to update vala
  - sudo add-apt-repository -y ppa:ricotz/testing 
  - sudo apt-get update
  - sudo apt-get install valac libgtk-3-dev glib2.0

script:
  - . setup_env_linux.sh
  - python2 waf configure
  - python2 waf
